apiVersion: v1
kind: Service
metadata:
  name: frpa-service-nodeport
spec:
  selector:
      app: frp-adapter
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: NodePort
